### ISSUE TITLE
Unable to delete button in layout once added

### ISSUE THREAD

**Issue by shahriarhus** [experiment322/controlloid-client#2]
Once I added button to the layout screen, I am unable to delete that button. In this screenshot, I have shrunk the left & right analog and moved it at top left and right respectively (just before L1 and R1 respectively) because I was unable to delete them in the first place.
![Screenshot](https://user-images.githubusercontent.com/34335070/56987166-4d7a8c00-6baa-11e9-96cd-fa90962866a0.jpeg)

I

**Comment by experiment322** [comment]
To delete a button you need to perform a pinch gesture.
Place one finger on the button and one further and bring them closer until the button becomes semi-transparent. Then lift your fingers and magic!

**Comment by rgarrigue** [comment]
At, was looking for this too. You should add this explanation in the home page

**Comment by experiment322** [comment]
I'm thinking to add some kind of animation (and maybe a message) when adding a button for the first time which points out, somehow, that the button can be deleted by pinching.
Other ideas are welcomed too.

**Comment by experiment322** [comment]
Improved in v1.2.0
