### ISSUE TITLE
(Bug) Can't tap two button simultaneously.

### ISSUE THREAD

**Issue by jokysatria** [experiment322/controlloid-client#20]
When tapping two buttons (for example x and o), only one button that tapped.

**Comment by ghost** [comment]
Can explain in detail?

With screenshot.

**Comment by jokysatria** [comment]
Sorry I can't pick a screenshot, since I tapped the buttons.

Step to reproduce :
1. First tap a button (for example is O)
2. Then tap another button (for example is X)

Expected result :
Both O and X are tapped.

Actual result :
Only O is tapped

**Comment by ghost** [comment]
@jokysatria I pressed 2 buttons at same time it worked smoothly. so, can you give more information ?

**Comment by jokysatria** [comment]
When I checked, I can press 2 buttons at the same time. But I can't press 2
buttons not at the same time (X first then O).

**Comment by ghost** [comment]
I can't understand what you're trying to say. Can you explain in detail? there are many application available for recording mobile's screen.

so , give a mobile's screen video 📽 or screen shot. 

This app works smoothly for me

**Comment by jokysatria** [comment]
Sorry make you confused.  I think the problem is my device.

**Comment by ghost** [comment]
@jokysatria yes , I also have the same issue. Its not your device problem.
