### ISSUE TITLE
Detect server on local lan

### ISSUE THREAD

**Issue by rgarrigue** [experiment322/controlloid-client#5]
It could be as simple as implementing a ping/pong function between server and client, and a port scan search over RFC1918 networks for the client to find server

**Comment by experiment322** [comment]
This is a planned feature that will be implemented in the close future.
Thanks for creating an issue to keep track of it.

> Useful resources
> [react-native-device-info](https://github.com/react-native-community/react-native-device-info)

**Comment by rgarrigue** [comment]
Thanks. A maybe easier feature but still saving time would be to save the last imputed value.

**Comment by experiment322** [comment]
Implemented in [v1.1.0](https://github.com/experiment322/controlloid-client/releases/tag/v1.1.0) using [react-native-network-info](https://github.com/pusherman/react-native-network-info) and performing a HTTP HEAD request over an IP range (considering a /24 subnet given the device IP) on port 31415.
Thus it won't work if the device is in a bigger network or in a smaller upper one, but almost all home networks are configured with a /24 subnet.

**Comment by rgarrigue** [comment]
Can you publish it on F-Droid ? Tried direct installation, didn't worked

**Comment by experiment322** [comment]
It doesn't work because it has different signatures. You need to wait a few days as fdroid has an automatic update mechanism based on git tags. It will be there soon!

**Comment by experiment322** [comment]
It will take a little more as there was a build issue.
